added file deletion safeguards if dependencies not met

diff --git a/compressMaker b/compressMaker
--- a/compressMaker
+++ b/compressMaker
@@ -79,35 +79,51 @@ done
 
 if [[ -z ${BASE} ]]
 then
+	echo -e 'Error: base directory not provided.\n' >&2
 	usage
 	exit 1
 fi
 
 if [[ ${COMPRESS} == 'true' && ${DECOMPRESS} == 'true' ]]
 then
+	echo -e 'Error: compression and decompression both selected.\n' >&2
+	usage
+	exit 1
+fi
+
+if [[ ${COMPRESS} == 'false' && ${DECOMPRESS} == 'false' ]]
+then
+        echo -e 'Error: compression or decompression not selected.\n' >&2
+        usage
+        exit 1
+fi
+
+if ! [[ -x "$(command -v pigz)" ]]
+then
+	echo -e 'Error: pigz is not installed.\n' >&2
 	usage
 	exit 1
 fi
 
 if [[ ${COMPRESS} == 'true' ]]
 then
-	pigz -${LEVEL} -p ${THREAD} ${BASE}/*_master_datastore_index.log
-	tar cf - ${BASE}/mpi_blastdb | pigz -${LEVEL} -p ${THREAD} > ${BASE}/mpi_blastdb.tar.gz
-	datastore=`find ${BASE} -type d -name "*_datastore"`
-	tar cf - ${datastore} | pigz -${LEVEL} -p ${THREAD} > ${datastore}.tar.gz
+	pigz -${LEVEL} -p ${THREAD} ${BASE}/*_master_datastore_index.log &&
+	tar cf - ${BASE}/mpi_blastdb | pigz -${LEVEL} -p ${THREAD} > ${BASE}/mpi_blastdb.tar.gz &&
+	datastore=`find ${BASE} -type d -name "*_datastore"` &&
+	tar cf - ${datastore} | pigz -${LEVEL} -p ${THREAD} > ${datastore}.tar.gz &&
 	rm -rf ${BASE}/mpi_blastdb ${datastore}
 fi
 
 if [[ ${DECOMPRESS} == 'true' ]]
 then
-	pigz -d -p ${THREAD} ${BASE}/*_master_datastore_index.log.gz
-	root=`basename ${BASE}/mpi_blastdb.tar.gz .tar.gz`
-	cmd="pigz -dc -p ${THREAD} ${BASE}/mpi_blastdb.tar.gz | tar xf - > ${BASE}/${root}"
-	eval $cmd
-	rm ${BASE}/mpi_blastdb.tar.gz
-	datastore=`find ${BASE} -type f -name "*_datastore.tar.gz"`
-	root=`basename ${datastore} .tar.gz`
-	cmd="pigz -dc -p ${THREAD} ${datastore} | tar xf - > ${BASE}/${root}"
-	eval $cmd
+	pigz -d -p ${THREAD} ${BASE}/*_master_datastore_index.log.gz &&
+	root=`basename ${BASE}/mpi_blastdb.tar.gz .tar.gz`&&
+	cmd="pigz -dc -p ${THREAD} ${BASE}/mpi_blastdb.tar.gz | tar xf - > ${BASE}/${root}" &&
+	eval $cmd &&
+	rm ${BASE}/mpi_blastdb.tar.gz &&
+	datastore=`find ${BASE} -type f -name "*_datastore.tar.gz"` &&
+	root=`basename ${datastore} .tar.gz` &&
+	cmd="pigz -dc -p ${THREAD} ${datastore} | tar xf - > ${BASE}/${root}" &&
+	eval $cmd &&
 	rm ${datastore}
 fi
diff --git a/compressRepMod b/compressRepMod
--- a/compressRepMod
+++ b/compressRepMod
@@ -79,40 +79,57 @@ done
 
 if [[ -z ${BASE} ]]
 then
+	echo -e 'Error: base directory not provided.\n' >&2
 	usage
 	exit 1
 fi
 
 if [[ ${COMPRESS} == 'true' && ${DECOMPRESS} == 'true' ]]
 then
+	echo -e 'Error: compression and decompression both selected.\n' >&2
 	usage
 	exit 1
 fi
 
+if [[ ${COMPRESS} == 'false' && ${DECOMPRESS} == 'false' ]]
+then
+        echo -e 'Error: compression or decompression not selected.\n' >&2
+        usage
+        exit 1
+fi
+
+if ! [[ -x "$(command -v pigz)" ]]
+then
+	echo -e 'Error: pigz is not installed.\n' >&2
+	usage
+	exit 1
+fi
+
+
 if [[ ${COMPRESS} == 'true' ]]
 then
-	pigz -${LEVEL} -p ${THREAD} ${BASE}/consensi.fa.classified
-	pigz -${LEVEL} -p ${THREAD} ${BASE}/consensi.fa
-	pigz -${LEVEL} -p ${THREAD} ${BASE}/consensi.fa.masked
-	pigz -${LEVEL} -p ${THREAD} ${BASE}/families-classified.stk
-	pigz -${LEVEL} -p ${THREAD} ${BASE}/families.stk
+	pigz -${LEVEL} -p ${THREAD} ${BASE}/consensi.fa.classified &&
+	pigz -${LEVEL} -p ${THREAD} ${BASE}/consensi.fa &&
+	pigz -${LEVEL} -p ${THREAD} ${BASE}/consensi.fa.masked &&
+	pigz -${LEVEL} -p ${THREAD} ${BASE}/families-classified.stk &&
+	pigz -${LEVEL} -p ${THREAD} ${BASE}/families.stk &&
 	for round in `find ${BASE} -type d -name round-?`
 	do
-		tar cf - ${round} | pigz -${LEVEL} -p ${THREAD} > ${round}.tar.gz
+		tar cf - ${round} | pigz -${LEVEL} -p ${THREAD} > ${round}.tar.gz &&
 		rm -rf ${round}
 	done	
 fi
 
 if [[ ${DECOMPRESS} == 'true' ]]
 then
-        pigz -d -p ${THREAD} ${BASE}/consensi.fa.classified.gz
-        pigz -d -p ${THREAD} ${BASE}/consensi.fa.gz
-        pigz -d -p ${THREAD} ${BASE}/consensi.fa.masked.gz
-        pigz -d -p ${THREAD} ${BASE}/families-classified.stk.gz
-        pigz -d -p ${THREAD} ${BASE}/families.stk.gz
+        pigz -d -p ${THREAD} ${BASE}/consensi.fa.classified.gz &&
+        pigz -d -p ${THREAD} ${BASE}/consensi.fa.gz &&
+        pigz -d -p ${THREAD} ${BASE}/consensi.fa.masked.gz &&
+        pigz -d -p ${THREAD} ${BASE}/families-classified.stk.gz &&
+        pigz -d -p ${THREAD} ${BASE}/families.stk.gz &&
         for round in `find ${BASE} -type f -name round-?.tar.gz`
         do
-		root=`basename ${round} .tar.gz`
+		root=`basename ${round} .tar.gz` &&
                 pigz -dc -p ${THREAD} ${round} | tar xf - > ${BASE}/${root}
 		rm ${round}
         done
diff --git a/compressSupernova b/compressSupernova
--- a/compressSupernova
+++ b/compressSupernova
@@ -83,42 +83,59 @@ done
 
 if [[ -z ${BASE} ]]
 then
+	echo -e 'Error: base directory not provided.\n' >&2
 	usage
 	exit 1
 fi
 
 if [[ ${COMPRESS} == 'true' && ${DECOMPRESS} == 'true' ]]
 then
+	echo -e 'Error: compression and decompression both selected.\n' >&2
 	usage
 	exit 1
 fi
 
+if [[ ${COMPRESS} == 'false' && ${DECOMPRESS} == 'false' ]]
+then
+        echo -e 'Error: compression or decompression not selected.\n' >&2
+        usage
+        exit 1
+fi
+
+if ! [[ -x "$(command -v pigz)" ]]
+then
+	echo -e 'Error: pigz is not installed.\n' >&2
+	usage
+	exit 1
+fi
+
+
 if [[ ${COMPRESS} == 'true' ]]
 then
-	tar cf - ${BASE}/outs/assembly/a.48 | pigz -${LEVEL} -p ${THREAD} > ${BASE}/outs/assembly/a.48.tar.gz
-	rm -rf ${BASE}/outs/assembly/a.48
-	tar cf - ${BASE}/outs/assembly/a.base | pigz -${LEVEL} -p ${THREAD} > ${BASE}/outs/assembly/a.base.tar.gz
-	rm -rf ${BASE}/outs/assembly/a.base
-	tar cf - ${BASE}/outs/assembly/a.patched | pigz -${LEVEL} -p ${THREAD} > ${BASE}/outs/assembly/a.patched.tar.gz
-	rm -rf ${BASE}/outs/assembly/a.patched
-	tar cf - ${BASE}/outs/assembly/data | pigz -${LEVEL} -p ${THREAD} > ${BASE}/outs/assembly/data.tar.gz
-	rm -rf ${BASE}/outs/assembly/data
+	tar cf - ${BASE}/outs/assembly/a.48 | pigz -${LEVEL} -p ${THREAD} > ${BASE}/outs/assembly/a.48.tar.gz &&
+	rm -rf ${BASE}/outs/assembly/a.48 &&
+	tar cf - ${BASE}/outs/assembly/a.base | pigz -${LEVEL} -p ${THREAD} > ${BASE}/outs/assembly/a.base.tar.gz &&
+	rm -rf ${BASE}/outs/assembly/a.base &&
+	tar cf - ${BASE}/outs/assembly/a.patched | pigz -${LEVEL} -p ${THREAD} > ${BASE}/outs/assembly/a.patched.tar.gz &&
+	rm -rf ${BASE}/outs/assembly/a.patched &&
+	tar cf - ${BASE}/outs/assembly/data | pigz -${LEVEL} -p ${THREAD} > ${BASE}/outs/assembly/data.tar.gz &&
+	rm -rf ${BASE}/outs/assembly/data &&
 
-	pigz -${LEVEL} -p ${THREAD} ${BASE}/outs/assembly/a.cpaths
+	pigz -${LEVEL} -p ${THREAD} ${BASE}/outs/assembly/a.cpaths &&
 	pigz -${LEVEL} -p ${THREAD} ${BASE}/outs/assembly/closures.fastb
 fi
 
 if [[ ${DECOMPRESS} == 'true' ]]
 then
-	pigz -dc -p ${THREAD} ${BASE}/outs/assembly/a.48.tar.gz | tar xf - > ${BASE}/outs/assembly/a.48
-	rm ${BASE}/outs/assembly/a.48.tar.gz
-	pigz -dc -p ${THREAD} ${BASE}/outs/assembly/a.base.tar.gz | tar xf - > ${BASE}/outs/assembly/a.base
-	rm ${BASE}/outs/assembly/a.base.tar.gz
-	pigz -dc -p ${THREAD} ${BASE}/outs/assembly/a.patched.tar.gz | tar xf - > ${BASE}/outs/assembly/a.patched
-	rm ${BASE}/outs/assembly/a.patched.tar.gz
-	pigz -dc -p ${THREAD} ${BASE}/outs/assembly/data.tar.gz | tar xf - > ${BASE}/outs/assembly/data
-	rm ${BASE}/outs/assembly/data.tar.gz
+	pigz -dc -p ${THREAD} ${BASE}/outs/assembly/a.48.tar.gz | tar xf - > ${BASE}/outs/assembly/a.48 &&
+	rm ${BASE}/outs/assembly/a.48.tar.gz &&
+	pigz -dc -p ${THREAD} ${BASE}/outs/assembly/a.base.tar.gz | tar xf - > ${BASE}/outs/assembly/a.base &&
+	rm ${BASE}/outs/assembly/a.base.tar.gz &&
+	pigz -dc -p ${THREAD} ${BASE}/outs/assembly/a.patched.tar.gz | tar xf - > ${BASE}/outs/assembly/a.patched &&
+	rm ${BASE}/outs/assembly/a.patched.tar.gz &&
+	pigz -dc -p ${THREAD} ${BASE}/outs/assembly/data.tar.gz | tar xf - > ${BASE}/outs/assembly/data &&
+	rm ${BASE}/outs/assembly/data.tar.gz &&
 
-	pigz -d -p ${THREAD} ${BASE}/outs/assembly/a.cpaths.gz
+	pigz -d -p ${THREAD} ${BASE}/outs/assembly/a.cpaths.gz &&
         pigz -d -p ${THREAD} ${BASE}/outs/assembly/closures.fastb.gz
 fi
diff --git a/compressTrinity b/compressTrinity
--- a/compressTrinity
+++ b/compressTrinity
@@ -82,81 +82,101 @@ done
 
 if [[ -z ${BASE} ]]
 then
+	echo -e 'Error: base directory not provided.\n' >&2
 	usage
 	exit 1
 fi
 
 if [[ ${COMPRESS} == 'true' && ${DECOMPRESS} == 'true' ]]
 then
+	echo -e 'Error: compression and decompression both selected.\n' >&2
 	usage
 	exit 1
 fi
+
+if [[ ${COMPRESS} == 'false' && ${DECOMPRESS} == 'false' ]]
+then
+        echo -e 'Error: compression or decompression not selected.\n' >&2
+        usage
+        exit 1
+fi
+
+if ! [[ -x "$(command -v pigz)" ]]
+then
+	echo -e 'Error: pigz is not installed.\n' >&2
+	usage
+	exit 1
+fi
+
 
 if [[ ${COMPRESS} == 'true' ]]
 then
 # normal Trinity mode
         if [[ -f ${BASE}/Trinity.fasta ]]
         then
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/both.fa
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/inchworm.fa
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/jellyfish.kmers.25.asm.fa
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/partitioned_reads.files.list
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/recursive_trinity.cmds.completed
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/recursive_trinity.cmds
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/scaffolding_entries.sam
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/Trinity.fasta.gene_trans_map
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/Trinity.fasta
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/both.fa &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/inchworm.fa &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/jellyfish.kmers.25.asm.fa &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/partitioned_reads.files.list &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/recursive_trinity.cmds.completed &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/recursive_trinity.cmds &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/scaffolding_entries.sam &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/Trinity.fasta.gene_trans_map &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/Trinity.fasta &&
 
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/bundled_iworm_contigs.fasta
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/GraphFromIwormFasta.out
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/inchworm.fa.min100.?.bt2
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/inchworm.fa.min100
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/inchworm.fa.min100.rev.?.bt2
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/iworm_cluster_welds_graph.txt
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/iworm_cluster_welds_graph.txt.sorted
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/iworm_cluster_welds_graph.txt.sorted.wIwormNames
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/iworm_scaffolds.txt
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/readsToComponents.out
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/readsToComponents.out.sort
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/bundled_iworm_contigs.fasta &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/GraphFromIwormFasta.out &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/inchworm.fa.min100.?.bt2 &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/inchworm.fa.min100 &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/inchworm.fa.min100.rev.?.bt2 &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/iworm_cluster_welds_graph.txt &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/iworm_cluster_welds_graph.txt.sorted &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/iworm_cluster_welds_graph.txt.sorted.wIwormNames &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/iworm_scaffolds.txt &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/readsToComponents.out &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/chrysalis/readsToComponents.out.sort &&
+
+                tar cf - ${BASE}/read_partitions | pigz -${LEVEL} -p ${THREAD} > ${BASE}/read_partitions.tar.gz &&
+                rm -rf ${BASE}/read_partitions &&
 
 		pigz -${LEVEL} -p ${THREAD} ${BASE}/insilico_read_normalization/*.fq
 	
-		tar cf - ${BASE}/read_partitions | pigz -${LEVEL} -p ${THREAD} > ${BASE}/read_partitions.tar.gz
-		rm -rf ${BASE}/read_partitions
 # reference guided Trinity mode
         elif [[ -f ${BASE}/Trinity-GG.fasta ]]
         then
                 for dir in `find ${base} -type d -name "Dir_*_merged_stranded.bam.norm_200.bam.?.sam.minC1.gff"`
                 do
-                        cmd="tar cf - ${dir} | pigz -${LEVEL} -p ${THREAD} > ${dir}.tar.gz"
-                        eval $cmd
+                        cmd="tar cf - ${dir} | pigz -${LEVEL} -p ${THREAD} > ${dir}.tar.gz" &&
+                        eval $cmd &&
                         rm -rf ${dir}
                 done
 
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/Dir_*_merged_stranded.bam.norm_200.bam.-.sam.minC1.gff.listing
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/Dir_*_merged_stranded.bam.norm_200.bam.+.sam.minC1.gff.listing
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/read_files.list
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.frag_coords
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.frag_coords
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.frag_coverage.wig
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.frag_coverage.wig
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.minC1.gff
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.minC1.gff
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.read_coords
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.read_coords
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.read_coords.sort_by_readname
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.read_coords.sort_by_readname
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/trinity_GG.cmds
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/trinity_GG.cmds.completed
-		pigz -${LEVEL} -p ${THREAD} ${BASE}/Trinity-GG.fasta
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/Dir_*_merged_stranded.bam.norm_200.bam.-.sam.minC1.gff.listing &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/Dir_*_merged_stranded.bam.norm_200.bam.+.sam.minC1.gff.listing &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/read_files.list &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.frag_coords &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.frag_coords &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.frag_coverage.wig &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.frag_coverage.wig &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.minC1.gff &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.minC1.gff &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.read_coords &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.read_coords &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.read_coords.sort_by_readname &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.read_coords.sort_by_readname &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/trinity_GG.cmds &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/trinity_GG.cmds.completed &&
+		pigz -${LEVEL} -p ${THREAD} ${BASE}/Trinity-GG.fasta &&
 		pigz -${LEVEL} -p ${THREAD} ${BASE}/Trinity-GG.fasta.gene_trans_map
 
         else
-                echo -e "\nError: Cannot detect the type of Trinity run to compress. Please ensure that one of the Trinity files is provided in the base directory:"
+                echo -e "Error: Cannot detect the type of Trinity run to compress. Please ensure that one of the Trinity files is provided in the base directory:"
 		echo -e "1. Trinity.fasta must be present for the normal Trinity mode"
 		echo -e "2. Trinity-GG.fasta must be present for the genome-guided Trinity mode.\n"
+		usage
+        	exit 1
 	fi
 fi
 
@@ -165,68 +185,71 @@ then
 # normal Trinity mode
         if [[ -f ${BASE}/Trinity.fasta.gz ]]
 	then
-		pigz -d -p ${THREAD} ${BASE}/both.fa.gz
-        	pigz -d -p ${THREAD} ${BASE}/inchworm.fa.gz
-	        pigz -d -p ${THREAD} ${BASE}/jellyfish.kmers.25.asm.fa.gz
-       		pigz -d -p ${THREAD} ${BASE}/partitioned_reads.files.list.gz
-	        pigz -d -p ${THREAD} ${BASE}/recursive_trinity.cmds.completed.gz
-	        pigz -d -p ${THREAD} ${BASE}/recursive_trinity.cmds.gz
-	        pigz -d -p ${THREAD} ${BASE}/scaffolding_entries.sam.gz
-	        pigz -d -p ${THREAD} ${BASE}/Trinity.fasta.gene_trans_map.gz
-	        pigz -d -p ${THREAD} ${BASE}/Trinity.fasta.gz
+		pigz -d -p ${THREAD} ${BASE}/both.fa.gz &&
+        	pigz -d -p ${THREAD} ${BASE}/inchworm.fa.gz &&
+	        pigz -d -p ${THREAD} ${BASE}/jellyfish.kmers.25.asm.fa.gz &&
+       		pigz -d -p ${THREAD} ${BASE}/partitioned_reads.files.list.gz &&
+	        pigz -d -p ${THREAD} ${BASE}/recursive_trinity.cmds.completed.gz &&
+	        pigz -d -p ${THREAD} ${BASE}/recursive_trinity.cmds.gz &&
+	        pigz -d -p ${THREAD} ${BASE}/scaffolding_entries.sam.gz &&
+	        pigz -d -p ${THREAD} ${BASE}/Trinity.fasta.gene_trans_map.gz &&
+	        pigz -d -p ${THREAD} ${BASE}/Trinity.fasta.gz &&
 
-	        pigz -d -p ${THREAD} ${BASE}/chrysalis/bundled_iworm_contigs.fasta.gz
-	        pigz -d -p ${THREAD} ${BASE}/chrysalis/GraphFromIwormFasta.out.gz
-	        pigz -d -p ${THREAD} ${BASE}/chrysalis/inchworm.fa.min100.?.bt2.gz
-	        pigz -d -p ${THREAD} ${BASE}/chrysalis/inchworm.fa.min100.gz
-	        pigz -d -p ${THREAD} ${BASE}/chrysalis/inchworm.fa.min100.rev.?.bt2.gz
-	        pigz -d -p ${THREAD} ${BASE}/chrysalis/iworm_cluster_welds_graph.txt.gz
-	        pigz -d -p ${THREAD} ${BASE}/chrysalis/iworm_cluster_welds_graph.txt.sorted.gz
-	        pigz -d -p ${THREAD} ${BASE}/chrysalis/iworm_cluster_welds_graph.txt.sorted.wIwormNames.gz
-	        pigz -d -p ${THREAD} ${BASE}/chrysalis/iworm_scaffolds.txt.gz
-	        pigz -d -p ${THREAD} ${BASE}/chrysalis/readsToComponents.out.gz
-	        pigz -d -p ${THREAD} ${BASE}/chrysalis/readsToComponents.out.sort.gz
+	        pigz -d -p ${THREAD} ${BASE}/chrysalis/bundled_iworm_contigs.fasta.gz &&
+	        pigz -d -p ${THREAD} ${BASE}/chrysalis/GraphFromIwormFasta.out.gz &&
+	        pigz -d -p ${THREAD} ${BASE}/chrysalis/inchworm.fa.min100.?.bt2.gz &&
+	        pigz -d -p ${THREAD} ${BASE}/chrysalis/inchworm.fa.min100.gz &&
+	        pigz -d -p ${THREAD} ${BASE}/chrysalis/inchworm.fa.min100.rev.?.bt2.gz &&
+	        pigz -d -p ${THREAD} ${BASE}/chrysalis/iworm_cluster_welds_graph.txt.gz &&
+	        pigz -d -p ${THREAD} ${BASE}/chrysalis/iworm_cluster_welds_graph.txt.sorted.gz &&
+	        pigz -d -p ${THREAD} ${BASE}/chrysalis/iworm_cluster_welds_graph.txt.sorted.wIwormNames.gz &&
+	        pigz -d -p ${THREAD} ${BASE}/chrysalis/iworm_scaffolds.txt.gz &&
+	        pigz -d -p ${THREAD} ${BASE}/chrysalis/readsToComponents.out.gz &&
+	        pigz -d -p ${THREAD} ${BASE}/chrysalis/readsToComponents.out.sort.gz &&
+
+                root=`basename ${BASE}/read_partitions.tar.gz .tar.gz` &&
+                cmd="pigz -dc -p ${THREAD} ${BASE}/read_partitions.tar.gz | tar xf - > ${BASE}/${root}" &&
+                eval $cmd &&
+                rm ${BASE}/read_partitions.tar.gz &&
 
 	        pigz -d -p ${THREAD} ${BASE}/insilico_read_normalization/*.fq.gz
 
-		root=`basename ${BASE}/read_partitions.tar.gz .tar.gz`
-	        cmd="pigz -dc -p ${THREAD} ${BASE}/read_partitions.tar.gz | tar xf - > ${BASE}/${root}"
-	        eval $cmd
-		rm ${BASE}/read_partitions.tar.gz
 # reference guided Trinity mode
 	elif [[ -f ${BASE}/Trinity-GG.fasta.gz ]]
 	then
                 for tarball in `find ${base} -type f -name "Dir_*_merged_stranded.bam.norm_200.bam.?.sam.minC1.gff.tar.gz"`
                 do
-			root=`basename ${tarball} .tar.gz`
-                        cmd="pigz -dc -p ${THREAD} ${tarball} | tar xf - > ${BASE}/${root}"
-                        eval $cmd
+			root=`basename ${tarball} .tar.gz` &&
+                        cmd="pigz -dc -p ${THREAD} ${tarball} | tar xf - > ${BASE}/${root}" &&
+                        eval $cmd &&
                         rm -rf ${tarball}
                 done
 
-		pigz -d -p ${THREAD} ${BASE}/Dir_*_merged_stranded.bam.norm_200.bam.-.sam.minC1.gff.listing.gz
-		pigz -d -p ${THREAD} ${BASE}/Dir_*_merged_stranded.bam.norm_200.bam.+.sam.minC1.gff.listing.gz
-		pigz -d -p ${THREAD} ${BASE}/read_files.list.gz
-		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.gz
-		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.gz
-		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.frag_coords.gz
-		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.frag_coords.gz
-		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.frag_coverage.wig.gz
-		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.frag_coverage.wig.gz
-		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.minC1.gff.gz
-		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.minC1.gff.gz
-		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.read_coords.gz
-		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.read_coords.gz
-		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.read_coords.sort_by_readname.gz
-		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.read_coords.sort_by_readname.gz
-		pigz -d -p ${THREAD} ${BASE}/trinity_GG.cmds.gz
-		pigz -d -p ${THREAD} ${BASE}/trinity_GG.cmds.completed.gz
-		pigz -d -p ${THREAD} ${BASE}/Trinity-GG.fasta.gz
+		pigz -d -p ${THREAD} ${BASE}/Dir_*_merged_stranded.bam.norm_200.bam.-.sam.minC1.gff.listing.gz &&
+		pigz -d -p ${THREAD} ${BASE}/Dir_*_merged_stranded.bam.norm_200.bam.+.sam.minC1.gff.listing.gz &&
+		pigz -d -p ${THREAD} ${BASE}/read_files.list.gz &&
+		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.gz &&
+		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.gz &&
+		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.frag_coords.gz &&
+		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.frag_coords.gz &&
+		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.frag_coverage.wig.gz &&
+		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.frag_coverage.wig.gz &&
+		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.minC1.gff.gz &&
+		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.minC1.gff.gz &&
+		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.read_coords.gz &&
+		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.read_coords.gz &&
+		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.-.sam.read_coords.sort_by_readname.gz &&
+		pigz -d -p ${THREAD} ${BASE}/*_merged_stranded.bam.norm_200.bam.+.sam.read_coords.sort_by_readname.gz &&
+		pigz -d -p ${THREAD} ${BASE}/trinity_GG.cmds.gz &&
+		pigz -d -p ${THREAD} ${BASE}/trinity_GG.cmds.completed.gz &&
+		pigz -d -p ${THREAD} ${BASE}/Trinity-GG.fasta.gz &&
 		pigz -d -p ${THREAD} ${BASE}/Trinity-GG.fasta.gene_trans_map.gz
 
 	else
-	        echo -e "\nError: Cannot detect the type of Trinity run to decompress. Please ensure that one of the Trinity files is present in the base directory:"
+	        echo -e "Error: Cannot detect the type of Trinity run to decompress. Please ensure that one of the Trinity files is present in the base directory:"
                 echo -e "1. Trinity.fasta.gz must be present for the normal Trinity mode"
                 echo -e "2. Trinity-GG.fasta.gz must be present for the genome-guided Trinity mode.\n"
+		usage
+        	exit 1
 	fi
 fi
